name: CMake Multi-Platform Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang, cl]
        build_type: [Release, Debug]
        shared_libs: [ON, OFF]
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
          - os: ubuntu-latest
            compiler: cl
          - os: macos-latest
            compiler: gcc
          - os: macos-latest
            compiler: cl
        include:
          - os: ubuntu-latest
            compiler: gcc
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            compiler: clang
            c_compiler: clang
            cpp_compiler: clang++
          - os: windows-latest
            compiler: cl
            c_compiler: cl
            cpp_compiler: cl
          - os: macos-latest
            compiler: clang
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies on macOS
      if: runner.os == 'macOS'
      run: brew install autoconf

    # ВАЖНО: укажите правильный путь к vcpkg.json
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgJsonGlob: 'Light/vcpkg.json'   # если vcpkg.json лежит в папке Light

    - name: Set VCPKG_ROOT
      shell: bash
      run: echo "VCPKG_ROOT=${{ github.workspace }}/vcpkg" >> $GITHUB_ENV

    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DBUILD_SHARED_LIBS=${{ matrix.shared_libs }}
        -DBUILD_TESTS=ON
        -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
        -S Light

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    # Копируем все DLL на Windows в папку с тестами (чтобы исполняемый файл нашёл зависимости)
    - name: Copy DLLs to test directory (Windows)
      if: runner.os == 'Windows'
      run: |
        mkdir -Force build\${{ matrix.build_type }}
        copy build\vcpkg_installed\x64-windows\bin\*.dll build\${{ matrix.build_type }}\
      shell: pwsh

    # Прямой запуск тестов (без ctest)
    - name: Run tests
      working-directory: build
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          ./${{ matrix.build_type }}/lightlib_tests.exe
        else
          ./${{ matrix.build_type }}/lightlib_tests
        fi
      shell: bash